syntax = "proto3";
package channel;
option java_package = "com.drocsid.grpc.proto";
option java_multiple_files = true;
import "common.proto";
import "message.proto";


service ChannelService {
  rpc GetChannel(ChannelId) returns (Channel);
  rpc UpdateChannel(UpdateChannelRequest) returns (common.ResponseMessage);

  rpc CreateMessage(CreateMessageRequest) returns (common.ResponseMessage);
  rpc DeleteMessage(message.MessageId) returns (common.ResponseMessage);
  rpc GetLastMessage(ChannelId) returns (message.Message);
  rpc GetAllMessages(ChannelId) returns (message.MessageList);
}

message Channel {
  string id = 1;
  string name = 2;
  repeated message.Message messages = 3;
  string guildId = 4;
}

message ChannelId {
  string userId = 1;
  string id = 2;
}

message UpdateChannelRequest {
  string user_id = 1;
  string id = 2;
  string name = 4;
}

message ChannelList {
  repeated Channel channels = 1;
}

message CreateMessageRequest {
  string userId = 1;
  string authorId = 2;
  string authorName = 3;
  string content = 4;
  string channelId = 5;
}
