syntax = "proto3";
package guild;
option java_package = "com.drocsid.grpc.proto";
option java_multiple_files = true;
import "common.proto";
import "role.proto";
import "guild_user.proto";
import "user.proto";
import "channel.proto";


service GuildService {
  // basic management
  rpc CreateGuild(CreateGuildRequest) returns (Guild);
  rpc GetGuild(GuildInfoReq) returns (Guild);
  rpc UpdateGuild(UpdateGuildRequest) returns (Guild);
  rpc DeleteGuild(GuildInfoReq) returns (common.ResponseMessage);
  rpc GetAllGuilds(user.UserId) returns (GuildList);
  rpc GetAllChannels(GuildInfoReq) returns (channel.ChannelList);

  // role management
  rpc GetRole(role.RoleReq) returns (role.Role);
  rpc CreateRole(role.CreateRoleReq) returns (role.Role);
  rpc GetRoles(GuildInfoReq) returns (role.RoleList);
  rpc UpdateRole(role.UpdateRoleReq) returns (role.Role);

  // channel creation
  rpc CreateChannel(channel.CreateChannelRequest) returns (channel.Channel);

  // guild user management
  rpc AddUser(guild_user.AddUser) returns (guild_user.GuildUser);
  rpc UpdateUser(guild_user.UpdateUserReq) returns (guild_user.GuildUser); // future
  rpc GetUser(guild_user.GuildUserReq) returns (guild_user.GuildUser);
  rpc GetUsers(GuildInfoReq) returns (guild_user.GuildUserList);
  rpc DeleteUser(guild_user.GuildUserReq) returns (common.ResponseMessage);
}

message Guild {
  string guild_id = 1;
  string name = 2;
  string icon = 3; // not used, future
  string owner_id = 4;
  repeated role.Role roles = 5;
}

message CreateGuildRequest {
  string token = 1;
  string name = 2;
  string icon = 3; // not used, future
}

message GuildInfoReq {
  string guild_id = 1;
  string token = 2;
}

message UpdateGuildRequest {
  string token = 1;
  Guild guild = 2;
}

message GuildList {
  repeated Guild guilds = 1;
}
