syntax = "proto3";
package guild;
option java_package = "com.drocsid.grpc.proto";
option java_multiple_files = true;
import "common.proto";
import "user.proto";
import "channel.proto";


service GuildService {
  rpc CreateGuild(CreateGuildRequest) returns (common.ResponseMessage);
  rpc GetGuild(GuildId) returns (Guild);
  rpc UpdateGuild(UpdateGuildRequest) returns (common.ResponseMessage);
  rpc ChangeGuildOwner(GuildUserInfo) returns (common.ResponseMessage);
  rpc DeleteGuild(GuildId) returns (common.ResponseMessage);
  rpc GetAllGuilds(user.UserId) returns (GuildList);

  rpc CreateChannel(CreateChannelRequest) returns (common.ResponseMessage);
  rpc DeleteChannel(DeleteChannelRequest) returns (common.ResponseMessage);
  rpc GetAllChannels(GuildId) returns (channel.ChannelList);

  rpc AddUser(GuildUserInfo) returns (common.ResponseMessage);
  rpc RemoveUser(GuildUserInfo) returns (common.ResponseMessage);
  rpc EditUserPermission(GuildEditUserRequest) returns (common.ResponseMessage);
}

message Guild {
  string id = 1;
  string name = 2;
  string icon = 3;
  string ownerId = 4;
  repeated channel.Channel channels = 5;
}

message CreateGuildRequest {
  string userId = 1;
  string name = 2;
  string icon = 3;
}

message GuildId {
  string userId = 1;
  string id = 2;
}

message UpdateGuildRequest {
  string user_id = 1;
  string id = 2;
  string name = 3;
  string icon = 4;
}

message GuildList {
  repeated Guild guilds = 1;
}

message GuildUserInfo {
  string userId = 1;
  string id = 2;
  string guildUserId = 3;
}

message GuildEditUserRequest {
  string userId = 1;
  string id = 2;
  string guildUserId = 3;
  int32 role = 4;
}

message CreateChannelRequest {
  string userId = 1;
  string id = 2;
  string name = 3;
  string guildId = 6;
}

message DeleteChannelRequest {
  string userId = 1;
  string id = 2;
  string guildId = 3;
}
