syntax = "proto3";
package message;
option java_package = "com.drocsid.grpc.proto";
option java_multiple_files = true;
import "common.proto";


service MessageService {
  rpc GetMessage(MessageId) returns (Message);
  rpc UpdateMessage(UpdateMessageRequest) returns (common.ResponseMessage);
}

message Message {
  string jwt = 1;
  string id = 2;
  string authorId = 3;
  string authorName = 4;
  string timestamp = 5;
  string content = 6;
  string channelId = 7;
}

message MessageId {
  string userId = 1;
  string id = 2;
}

message UpdateMessageRequest {
  string userId = 1;
  string id = 2;
  string authorName = 3;
  string content = 4;
}

message MessageList {
  repeated Message messages = 1;
}
