syntax = "proto3";
option java_package = "com.drocsid.grpc.proto";
option java_multiple_files = true;
package role;

message Role {
  string guild_role_id = 1;
  string role_name = 2;
  string permissions = 3;
}

message RoleList {
  repeated Role roles = 1;
}

message CreateRoleReq {
  string guild_id = 1;
  string role_name = 2;
  string permissions = 3;
  string caller_id = 4;
}

message UpdateRoleReq {
  string guild_id = 1;
  Role role = 2;
  string caller_id = 3;
}

message RoleReq {
  string guild_id = 1;
  string guild_role_id = 2;
  string caller_id = 3;
}