syntax = "proto3";
package user;
option java_package = "com.drocsid.grpc.proto";
option java_multiple_files = true;
import "common.proto";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (User);
  rpc GetUser(UserId) returns (User);
  rpc UpdateUser(UpdateUserRequest) returns (User);
  rpc DeleteUser(UserId) returns (common.ResponseMessage);
}

message User {
  string id = 1;
  string name = 2;
  string avatarHash = 3; // future
}

message CreateUserRequest {
  string name = 1;
}

message UserId {
  string token = 1;
}

message UpdateUserRequest {
  string token = 1;
  string name = 2;
  string avatarHash = 3; // future
}
