worker_processes  1;
events {
    worker_connections  1024;
}

http {
	sendfile off;
	keepalive_timeout 60;

	server {
		listen 8080;

		location / {
			proxy_pass https://frontend:5173;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /api
			proxy_pass http://backend:9090;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}
