pipeline {
    agent any
    
    environment {
        DOCKER_COMPOSE = 'docker-compose'
        MAVEN_OPTS = '-Dmaven.repo.local=.m2/repository'
        JAVA_HOME = '/opt/java/openjdk'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }
        
        stage('Build Backend') {
            steps {
                echo 'Building Spring gRPC Backend...'
                dir('spring_grpc') {
                    sh '''
                        java -version
                        mvn -version
                        mvn clean install
                    '''
                }
            }
        }
        
        stage('Test Backend') {
            steps {
                echo 'Running Backend Tests...'
                dir('spring_grpc') {
                    sh '''
                        mvn test
                    '''
                }
            }
            post {
                always {
                    junit(
                        testResults: '**/target/surefire-reports/*.xml',
                        allowEmptyResults: true,
                        skipPublishingChecks: true
                    )
                }
            }
        }
        
        stage('Build Frontend') {
            steps {
                echo 'Installing Frontend Dependencies...'
                dir('frontend') {
                    sh '''
                        npm ci
                        npm run build
                    '''
                }
            }
        }
        
        stage('Build Docker Images') {
            steps {
                echo 'Building Docker Images...'
                sh '''
                    docker-compose build
                '''
            }
        }
        
        stage('Deploy') {
            when {
                branch 'jenkins'
            }
            steps {
                echo 'Deploying Application...'
                sh '''
                    docker-compose down
                    docker-compose up -d
                '''
            }
        }
    }
    
    post {
        always {
            echo 'Cleaning up...'
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
